### ISSUE TITLE
Riff-Raff continuous deployment not firing...

### ISSUE THREAD

**Issue by rtyley** [guardian/deploy#246]
@philwills,  @tomverran and myself noticed that Subscriptions Frontend is not getting continuously deploye :crying_cat_face: 

For instance, build #1173, started in TeamCity at 30 Oct 15 15:03 (and the previous #1170), did not fire in Riffraff:

#### RiffRaff history
https://riffraff.gutools.co.uk/deployment/history?projectName=Subscriptions%3A%3Afrontend#
![image](https://cloud.githubusercontent.com/assets/52038/10850396/4cc34d38-7f1d-11e5-8565-21d27728efad.png)

#### Teamcity
https://teamcity.gutools.co.uk/viewType.html?buildTypeId=Subscriptions_Frontend&branch_Subscriptions=%3Cdefault%3E&tab=buildTypeStatusDiv
![image](https://cloud.githubusercontent.com/assets/52038/10850407/58589b6c-7f1d-11e5-853b-885963524123.png)

#### RiffRaff CD is set
https://riffraff.gutools.co.uk/deployment/continuous/c4425e1a-9b84-411c-8b9e-ed82ee72b570/edit

![image](https://cloud.githubusercontent.com/assets/52038/10850441/a2ec44e4-7f1d-11e5-8b26-3225e863c48c.png)

**Comment by philwills** [comment]
Good news, there's a correlated stack trace, so I have a clue about how to fix!

Bad news, it's from some really shonky not quite async code, so it might take a bit of work.

**Comment by philwills** [comment]
I think this has largely been addressed by #247. In the longer term we could do with revisiting that logic, but I'm going to close this for now. Feel free to reopen if you disagree.
